Compose finalizing
Curo-app/curo pull request #11
Opened 2023-04-03 11:37 UTC by rorione

Закончил компановку, добавил все переходы, экран share
Закостылил какие-то штуки для демо (в основном логика на мок-данных)
Из изменений внешних только календарь:
![image](https://user-images.githubusercontent.com/21989227/229498272-9af9596a-1351-4734-a142-68cffd588e7b.png)

2023-04-03 11:47 UTC, Ilya-Sib approved these changes, later dismissed

2023-04-03 18:03 UTC, KhoDis requested changes

2023-04-03 18:03 UTC, Feyyus commented on app/src/main/java/io/github/curo/data/NotePatchViewModel.kt
> +    fun empty(id: Int) {
Может назвать reset/clear?

2023-04-03 18:03 UTC, Feyyus commented on app/src/main/java/io/github/curo/ui/AppScreen.kt
> +                } ?: notePatchViewModel.empty(feedViewModel.items.maxOf(Note::id).inc())
Может лучше сделать метод makeNewNote или что-то такое? А то слишком сложная логика здесь

2023-04-03 18:03 UTC, Feyyus commented on app/src/main/java/io/github/curo/ui/AppScreen.kt
> +                if (notePatchViewModel.newCollection != null) {
За что этот if отвечает? За что отвечает newCollection?

2023-04-03 18:03 UTC, Feyyus commented on app/src/main/java/io/github/curo/ui/AppScreen.kt
> +                Screen.EditCollection -> outerNavHost.navigate(menu.route + "/My collection")
А можно что ли пробелы в route делать? И что такое `My collection`?

2023-04-03 18:03 UTC, Feyyus commented on app/src/main/java/io/github/curo/data/CalendarViewModel.kt
> +    fun updateOnFilters() {
Планируется ли в будущем вместо clear использовать мапу, полученную из `groupBy(Collection)`? Чтобы каждый раз не пришлось мапу чистить при нажатии на chip

2023-04-03 18:03 UTC, Feyyus commented on app/src/main/java/io/github/curo/ui/AppScreen.kt
>      innerNavController: NavHostController,
Может переименовать inner, outer так, чтобы было понятно, что зак контроллер конкретно? Или value class сделать? Так можно?

2023-04-03 18:03 UTC, Feyyus commented on app/src/main/java/io/github/curo/ui/AppScreen.kt
> +                content = if (currentRoute == BottomNavigationScreen.Calendar.route) {
Может сделать наружний Scaffold с BottomBar, в котором будет лежать кастомная страница (например, Calendar)? А уже кастомная страница будет содержать ещё один Scaffold с необходимым topBar? Тогда можно будет кастомизировать topBar для каждой страницы

Например, минус текущего подхода: SearchTopAppBar содержит информацию о месяцах, хотя с точки зрения логики, это странно

2023-04-03 18:03 UTC, Feyyus commented on app/src/main/java/io/github/curo/ui/base/Search.kt
> +                            if (text.length >= 2) {
Может в константу вынести?

2023-04-03 18:03 UTC, Feyyus commented on app/src/main/java/io/github/curo/ui/base/Search.kt
> +    onSearch: (String?) -> Unit = {},
Для чего nullable?

2023-04-03 18:03 UTC, Feyyus commented on app/src/main/java/io/github/curo/ui/screens/Collections.kt
> +            items(viewModel.collections) { item ->
Может переименовать item -> collection? Полегче читать код будет

2023-04-03 18:03 UTC, Feyyus commented on app/src/main/java/io/github/curo/ui/screens/SearchView.kt
> +        Feed(
Кажется, что оригинальный смысл Feed'а уже поменялся. Думаю, можно переименовать как-то абстрактнее

2023-04-03 19:23 UTC, RuslanZaripov requested changes

2023-04-03 19:23 UTC, RuslanZaripov commented on app/src/main/java/io/github/curo/data/CollectionPatchViewModel.kt
> +class CollectionPatchViewModel : FeedViewModel() {
это паттерн какой-то с Patch классами или твоя личная разработка?

2023-04-03 19:23 UTC, RuslanZaripov commented on app/src/main/java/io/github/curo/data/CalendarViewModel.kt
> +                val data = items
Может не data все-таки, а collections назвать?

2023-04-03 19:23 UTC, RuslanZaripov commented on app/src/main/java/io/github/curo/data/CalendarViewModel.kt
> +    override val items: List<Note>
Почему notes плохое название? Все ViewModel'и содержат поле items

2023-04-03 19:23 UTC, RuslanZaripov commented on app/src/main/java/io/github/curo/data/CalendarViewModel.kt
> +        val filteredNotes = super.items.filter { note ->
Кажется это плохое название, непонятно по какому признаку фильтруются заметки

2023-04-03 19:23 UTC, RuslanZaripov commented on app/src/main/java/io/github/curo/data/CalendarViewModel.kt
> +        val showedCollections = buildSet {
Может лучше selectedCollections?

2023-04-03 19:23 UTC, RuslanZaripov commented on app/src/main/java/io/github/curo/data/CollectionPatchViewModel.kt
> +        )
Такая логика: `clear()` и `addAll()` встречается много где, может вынести в extension function `.setAll()` в Util.kt?

2023-04-03 19:23 UTC, RuslanZaripov commented on app/src/main/java/io/github/curo/data/CollectionPatchViewModel.kt
> +            super.items.filter { item -> value.name in item.collections.map { it.name } }
`.map { it.name }` много где встречается, может вынести в extension function для `List<CollectionName>` типо `extractNames`

2023-04-03 19:23 UTC, RuslanZaripov commented on app/src/main/java/io/github/curo/data/CollectionPatchViewModel.kt
> +    fun set(value: CollectionName) {
value плохое название. Может collectionName тогда уже?

2023-04-03 19:23 UTC, RuslanZaripov commented on app/src/main/java/io/github/curo/data/CollectionViewModel.kt
> +                    .distinct()
Много где встречается такая логика, может вынести как-нибудь?

2023-04-03 19:23 UTC, RuslanZaripov commented on app/src/main/java/io/github/curo/data/CollectionViewModel.kt
> +                    .map { name ->
Опять name плохое название, может collectionName? на 30 строчке, например `name.name`

2023-04-03 19:23 UTC, RuslanZaripov commented on app/src/main/java/io/github/curo/data/CollectionViewModel.kt
> +        if (existing == -1) {
Magic constant. Может вынести `NOT_FOUND`?

2023-04-03 19:23 UTC, RuslanZaripov commented on app/src/main/java/io/github/curo/data/CollectionPreviewModel.kt
>      val name: String,
Тут не надо писать `CollectionName` вместо `String`, чтобы везде не писать `CollectionPreviewModel.name == CollectionName.name`.

2023-04-03 19:23 UTC, RuslanZaripov commented on app/src/main/java/io/github/curo/data/SearchViewModel.kt
> +                super.items.filter { item -> item.name.contains(value, true) }
Может добавить argument name для булеана?

2023-04-03 19:23 UTC, RuslanZaripov commented on app/src/main/java/io/github/curo/ui/AppScreen.kt
> +                notePatchViewModel.empty(-1)
Тут не надо константу NEW_ENTITY_ID использовать?

2023-04-15 10:53 UTC, rorione commented on app/src/main/java/io/github/curo/ui/AppScreen.kt
> +                if (notePatchViewModel.newCollection != null) {
Я наткнулся на непродуманный момент: если мы создаем коллекцию и при создании коллекции нажимаем создать заметку, то коллекция еще не создана, а вот заметка должна быть как-то привязана к ней. Поэтому добавил при создании заметки фиксированное поле с коллекцией (newCollection), если создаем заметку из коллекции.

2023-04-15 10:54 UTC, rorione commented on app/src/main/java/io/github/curo/ui/AppScreen.kt
> +                if (notePatchViewModel.newCollection != null) {
И типа если мы создали заметку внутри создании коллекции - этот if добавит созданную заметку в создаваемую коллекцию

2023-04-15 11:15 UTC, rorione commented on app/src/main/java/io/github/curo/data/CalendarViewModel.kt
> +    fun updateOnFilters() {
Да, мы прикрутим бдшку и через Flow будем подписываться на изменения и делать нормально

2023-04-15 11:19 UTC, rorione commented on app/src/main/java/io/github/curo/ui/AppScreen.kt
>      innerNavController: NavHostController,
Там value класс запарно делать из-за rememberNavHost (нужно создать экземпляр внутри remember, то есть скопипастить функцию лишнюю)

2023-04-15 11:22 UTC, rorione commented on app/src/main/java/io/github/curo/ui/AppScreen.kt
> +                content = if (currentRoute == BottomNavigationScreen.Calendar.route) {
На самом деле я гуглил насчет вложенных Scaffold и говорят что это не оч и советуют как раз состоянием менять контент топ-бара и боттом-бара.
https://stackoverflow.com/questions/71410351/jetpack-compose-nested-navigation-and-bottomappbar
Ну и формально SearchTopAppBar умеет показывать либо строку поиска, либо какой-то заголовок и кнопку поиска, так что я в праве внутрь класть в зависимости от состояния любую инфу

2023-04-15 11:23 UTC, rorione commented on app/src/main/java/io/github/curo/ui/AppScreen.kt
> +                content = if (currentRoute == BottomNavigationScreen.Calendar.route) {
Если ты считаешь что еще один Scaffold мастхев, то можно попробовать (но мне кажется там еще будет проигрыш по производительности, ибо рекомпоузить придется дофига элементов)

2023-04-15 11:24 UTC, rorione commented on app/src/main/java/io/github/curo/ui/base/Search.kt
> +    onSearch: (String?) -> Unit = {},
Если поисковая строка в режиме заголовка(календарь), то при нажатии на кнопку поиска будет вызвана эта функция с null в качестве аргумента

2023-04-15 11:26 UTC, rorione commented on app/src/main/java/io/github/curo/ui/screens/SearchView.kt
> +        Feed(
Ну по смыслу фид - это набор заметок. Так что мне норм. Можешь голосовалку сделать и потом переименуем

2023-04-15 11:27 UTC, rorione commented on app/src/main/java/io/github/curo/data/CollectionPatchViewModel.kt
> +class CollectionPatchViewModel : FeedViewModel() {
Ну типа у каждого экрана должна быть своя ViewModel, которая хранит состояния экрана. Это ViewModel для экрана создания\изменения заметки. Там лежат измененные, но еще не сохраненные в саму заметку данные.

2023-04-15 11:30 UTC, rorione commented on app/src/main/java/io/github/curo/data/CalendarViewModel.kt
> +        val filteredNotes = super.items.filter { note ->
не могу найти эту строку, видимо старая версия кода

2023-04-15 11:31 UTC, rorione commented on app/src/main/java/io/github/curo/data/CalendarViewModel.kt
> +        val showedCollections = buildSet {
аналогично не могу найти эту строку

2023-04-21 14:12 UTC, rorione commented
![image](https://user-images.githubusercontent.com/21989227/233656803-69ad13a5-c9aa-498d-b363-88cbd4ffab58.png)
![image](https://user-images.githubusercontent.com/21989227/233656843-d2364b10-4e2d-49de-86ca-9115621cf428.png)
![image](https://user-images.githubusercontent.com/21989227/233656952-bfa4795a-a9a8-4e43-9480-88f43c27649c.png)
![image](https://user-images.githubusercontent.com/21989227/233657025-3010cf03-c8fc-46cc-95cf-759d7bb1a6c4.png)

2023-04-22 07:32 UTC, Ilya-Sib approved these changes

2023-04-24 07:57 UTC, KhoDis approved these changes

2023-04-24 07:59 UTC, RuslanZaripov approved these changes

2023-04-24 08:00 UTC, merged