Database support
Curo-app/curo pull request #12
Opened 2023-04-22 18:00 UTC by Ilya-Sib

2023-04-24 08:32 UTC, KhoDis submitted a review, later dismissed

2023-04-24 08:47 UTC, rorione requested changes

2023-04-24 08:47 UTC, rorione commented on app/src/main/java/io/github/curo/database/AppDatabase.kt
> +                val instance = Room.databaseBuilder(
внутри synchronized нужна еще одна проверка на null для INSTANCE, иначе 2 раза может создаться, если в sync блок зайдут два потока поочерёдно

2023-04-24 08:47 UTC, rorione commented on app/src/main/java/io/github/curo/database/converter/Converters.kt
> +class Converters {
наверное object

2023-04-24 08:47 UTC, rorione commented on app/src/main/java/io/github/curo/database/entities/Note.kt
> +            Note(
а напомни плиз, чем отличаются Note и NotePreview? Мб для NotePreview ограничивать description при селекте?

2023-04-24 08:58 UTC, Ilya-Sib commented on app/src/main/java/io/github/curo/database/converter/Converters.kt
> +class Converters {
Для либы нужен класс

2023-04-24 08:59 UTC, Ilya-Sib commented on app/src/main/java/io/github/curo/database/entities/Note.kt
> +            Note(
Note - модель которая хранится у нас в базе, NotePreview - то, как мы хотим с ней работать

2023-04-24 09:12 UTC, Ilya-Sib commented on app/src/main/java/io/github/curo/database/AppDatabase.kt
> +                val instance = Room.databaseBuilder(
Согл, я это просто из гайда скопировал

2023-04-24 09:12 UTC, Ilya-Sib commented on app/src/main/java/io/github/curo/database/converter/Converters.kt
> +class Converters {
Хотя попробую поменять

2023-04-24 09:12 UTC, Ilya-Sib commented on app/src/main/java/io/github/curo/database/converter/Converters.kt
> +class Converters {
Я просто смотрел сгенереное и он там через new создает

2023-04-24 09:13 UTC, Ilya-Sib commented on app/src/main/java/io/github/curo/database/converter/Converters.kt
> +class Converters {
(генерит жабу)

2023-04-24 09:13 UTC, rorione commented on app/src/main/java/io/github/curo/database/converter/Converters.kt
> +class Converters {
так вроде ksp должно генерить kotlin

2023-04-24 09:14 UTC, rorione commented on app/src/main/java/io/github/curo/database/entities/Note.kt
> +            Note(
а в чем разница? для всех остальных сущностей у нас также 2 модели?

2023-04-24 09:15 UTC, rorione commented on app/src/main/java/io/github/curo/database/entities/Note.kt
> +            Note(
Я думал preview это note с обрезанным описанием, чтобы для отображения в фиде не подгружать заметки полностью

2023-04-24 09:15 UTC, rorione commented on app/src/main/java/io/github/curo/database/entities/Note.kt
> +            Note(
Ну и наверное из названия лучше убрать слово model, оно засоряет все и путается с viewModel

2023-04-24 19:26 UTC, Feyyus commented on app/src/main/java/io/github/curo/database/dao/NoteCollectionCrossRefDao.kt
> +    @Query("SELECT * FROM NoteCollectionCrossRef WHERE collection_name = :collectionName")
Почему в `@Query("SELECT * FROM...` CollectionDao есть `@Transaction`, а здесь нет?

2023-04-24 19:26 UTC, RuslanZaripov requested changes

2023-04-24 19:26 UTC, RuslanZaripov commented on app/src/main/java/io/github/curo/database/dao/NoteDao.kt
> +    @Transaction
А что @Transaction делает? Смотрел в доке, но понял слабо

2023-04-24 20:47 UTC, Ilya-Sib commented on app/src/main/java/io/github/curo/database/entities/Note.kt
> +            Note(
ну я считаю правильно что одна на показ, другая для бд, так что те, что хранятся - да, две

2023-04-24 20:47 UTC, Ilya-Sib commented on app/src/main/java/io/github/curo/database/entities/Note.kt
> +            Note(
название поправлю

2023-04-24 20:49 UTC, Ilya-Sib commented on app/src/main/java/io/github/curo/database/dao/NoteCollectionCrossRefDao.kt
> +    @Query("SELECT * FROM NoteCollectionCrossRef WHERE collection_name = :collectionName")
потому что тут идет запрос к одной таблице, а в collection dao он делает выборку сразу по 3
- ищет коллекции в Collections
- ссылки на связанные записи в NoteCollectionCrossRef 
- соеденяет Collections и Notes через NoteCollectionCrossRef

2023-04-24 20:49 UTC, Ilya-Sib commented on app/src/main/java/io/github/curo/database/dao/NoteCollectionCrossRefDao.kt
> +    @Query("SELECT * FROM NoteCollectionCrossRef WHERE collection_name = :collectionName")
может немного путать то, что запрос похож, но под капотом там сильно разное

2023-04-24 20:51 UTC, Ilya-Sib commented on app/src/main/java/io/github/curo/database/dao/NoteDao.kt
> +    @Transaction
Оно выполняет запрос\несколько запросов внутри транзакции, это достаточно популярное понятие в БД, подробнее можешь почитать [тут ](https://habr.com/ru/articles/537594/)

2023-04-29 02:31 UTC, re1nex commented on app/src/main/java/io/github/curo/database/AppDatabase.kt
> +                val instance = Room.databaseBuilder(
А вам точно нужна дополнительная синхронизация в AppDataBase.getDatabase ? 

Просто увидел только вызов в lazy, а он по-умолчанию синхронизирован, см https://kotlinlang.org/docs/delegated-properties.html#lazy-properties

Ну и реализация ленивой инициализации синглтона на основе холдера проще в реализации и соответсвенно влечет меньшую подверженность ошибкам https://en.wikipedia.org/wiki/Initialization-on-demand_holder_idiom

2023-04-29 17:12 UTC, rorione approved these changes

2023-05-01 15:03 UTC, KhoDis approved these changes

2023-05-01 15:39 UTC, merged