Note options
Curo-app/curo pull request #5
Opened 2023-03-18 09:55 UTC by rorione

- Note options implemented
- Feed checkboxes added

2023-03-18 10:07 UTC, rorione commented
Добавил чекбоксы в фид и сверстал настройки заметки
![image](https://user-images.githubusercontent.com/21989227/226099051-07421e98-c5ff-4a76-925d-2ca5d498f9e0.png)
![image](https://user-images.githubusercontent.com/21989227/226099105-e08efd53-8633-4d28-8af3-ffd9dec7e1cb.png)

2023-03-20 12:47 UTC, Ilya-Sib requested changes

2023-03-20 12:47 UTC, Ilya-Sib commented on app/src/main/java/io/github/curo/data/CollectionPreviewModel.kt
> -    val id: Int,
зачем? как ты будешь искать по коллекции?

2023-03-20 12:47 UTC, Ilya-Sib commented on app/src/main/java/io/github/curo/ui/base/Feed.kt
> +    viewModel: NoteViewModel,
а это норм внутрь модели класть viewModel? мб его отдельно передавать?

2023-03-20 12:47 UTC, Ilya-Sib commented on app/src/main/res/values/strings.xml
> +    <string name="done">Done</string>
а где вообще использование этого говна? а то я у себя этого не делал еще

2023-03-20 12:47 UTC, Ilya-Sib commented on app/src/main/java/io/github/curo/ui/base/Feed.kt
> +    viewModel: NoteViewModel,
он же по идее будет один на все модели фида

2023-03-20 12:48 UTC, rorione commented on app/src/main/java/io/github/curo/ui/base/Feed.kt
> +    viewModel: NoteViewModel,
что значит внутрь модели класть viewModel? тут модель лежит внутри viewModel, что норм

2023-03-20 12:48 UTC, rorione commented on app/src/main/res/values/strings.xml
> +    <string name="done">Done</string>
это потом для локализации

2023-03-20 13:55 UTC, Ilya-Sib commented on app/src/main/java/io/github/curo/ui/base/Feed.kt
> +    viewModel: NoteViewModel,
А, я не правильно понял куда ты это передал, вроде ок

2023-03-20 13:55 UTC, Ilya-Sib commented on app/src/main/java/io/github/curo/ui/base/Feed.kt
> +    viewModel: NoteViewModel,
Я подумал ты засунул view model в preview model

2023-03-20 13:55 UTC, Ilya-Sib commented on app/src/main/res/values/strings.xml
> +    <string name="done">Done</string>
Я понимаю, дай мне строку, где ты это используешь, а то я чет не понял

2023-03-20 13:56 UTC, Ilya-Sib approved these changes

2023-03-23 15:50 UTC, KhoDis approved these changes

2023-03-23 15:50 UTC, KhoDis commented on app/src/main/java/io/github/curo/data/CollectionViewModel.kt
> +                        id = Random.nextInt(),
Для чего нужен Random.nextInt? А если числа совпадут?

2023-03-23 15:50 UTC, KhoDis commented on app/src/main/java/io/github/curo/utils/Consts.kt
> +const val MAX_NOTE_COLLECTIONS_AMOUNT = 5
Может подобные вещи в xml какой-то выносить?

2023-03-23 16:01 UTC, rorione commented on app/src/main/java/io/github/curo/data/CollectionViewModel.kt
> +                        id = Random.nextInt(),
Ну это моковые данные, я просто не хочу придумывать id-шники сейчас + хочу быть уверенным, что сейчас оно со случайными работает

2023-03-23 16:03 UTC, rorione commented on app/src/main/java/io/github/curo/utils/Consts.kt
> +const val MAX_NOTE_COLLECTIONS_AMOUNT = 5
Ну в теории можно конфиг файл делать, но такое обычно делают, когда есть несколько пресетов (прод, дев, препрод). У нас же пресетов не будет и чтобы не заморачиваться с чтением констант из файла - предлагаю их прям тут делать. Строки мы как ресурс выносим чисто чтобы можно было локализацию делать, там не прокатит их пихать константами

2023-03-23 16:06 UTC, merged