Settings
Curo-app/curo pull request #6
Opened 2023-03-20 20:42 UTC by Ilya-Sib

![image](https://user-images.githubusercontent.com/79597667/226461116-16ea9ab5-0f1a-4153-8fda-4b78b0424f19.png)
![image](https://user-images.githubusercontent.com/79597667/226461164-7eefb4b4-738d-44db-8445-d67e9ad13f8e.png)
![image](https://user-images.githubusercontent.com/79597667/226461195-0d93d70a-14f5-487e-bf51-a8d52d03df3e.png)
так же скинул видео в ТГ

2023-03-20 22:08 UTC, rorione requested changes

2023-03-20 22:08 UTC, rorione commented on app/src/main/java/io/github/curo/data/MenuItem.kt
> +data class MenuItem(
@ Immutable

2023-03-20 22:08 UTC, rorione commented on app/src/main/java/io/github/curo/ui/base/NavigationMenu.kt
> +                    println("Clicked on ${it.title}")
???

2023-03-20 22:08 UTC, rorione commented on app/src/main/java/io/github/curo/ui/base/Settings.kt
> +fun SettingsContent(modifier: Modifier = Modifier) {
Надо бы сделать ViewModel и в ней state, который будет меняться в зависимости от выбранного пункта

2023-03-20 22:08 UTC, rorione commented on app/src/main/java/io/github/curo/ui/base/Settings.kt
> +    var textfieldSize by remember { mutableStateOf(Size.Zero) }
вот это говно не нужно, лучше сделай также, как у меня suggest меню работает в настройках заметки

2023-03-20 22:08 UTC, rorione commented on app/src/main/java/io/github/curo/ui/base/Settings.kt
> +        EmojiContainer(Emoji("\uD83C\uDF46"), size = 200F)
Лучше в ресурсы эмоджи

2023-03-20 22:14 UTC, Ilya-Sib commented on app/src/main/java/io/github/curo/ui/base/Settings.kt
> +        EmojiContainer(Emoji("\uD83C\uDF46"), size = 200F)
Это же просто затычка пока что, нет?)

2023-03-20 22:14 UTC, Ilya-Sib commented on app/src/main/java/io/github/curo/ui/base/NavigationMenu.kt
> +                    println("Clicked on ${it.title}")
Тут надо настроить переходы между экранами, на это у нас есть отдельная задача на последней неделе

2023-03-20 22:38 UTC, Ilya-Sib commented on app/src/main/java/io/github/curo/ui/base/Settings.kt
> +fun SettingsContent(modifier: Modifier = Modifier) {
логика, а сейчас делаем верстку

2023-03-23 15:14 UTC, rorione approved these changes, later dismissed

2023-03-23 16:13 UTC, RuslanZaripov commented on app/src/main/java/io/github/curo/ui/MainScreen.kt
> +    onSearchClick: (String) -> Unit = {},
правильно ли оставлять дефолтную реализацию, она же невалидная?

2023-03-23 16:13 UTC, RuslanZaripov commented on app/src/main/java/io/github/curo/ui/base/Settings.kt
> +    Column(modifier = modifier.padding(horizontal = 30.dp, vertical = 5.dp)) {
может лучше Surface Composable?

2023-03-23 20:52 UTC, Ilya-Sib commented on app/src/main/java/io/github/curo/ui/MainScreen.kt
> +    onSearchClick: (String) -> Unit = {},
Пока мы логику не делаем думаю да, да и это не мой компонент, я просто переименовал)

2023-03-23 20:52 UTC, Ilya-Sib commented on app/src/main/java/io/github/curo/ui/base/Settings.kt
> +    Column(modifier = modifier.padding(horizontal = 30.dp, vertical = 5.dp)) {
Кого?

2023-03-23 20:53 UTC, Ilya-Sib commented on app/src/main/java/io/github/curo/ui/base/Settings.kt
> +    Column(modifier = modifier.padding(horizontal = 30.dp, vertical = 5.dp)) {
Попробую поменять

2023-03-24 14:47 UTC, RuslanZaripov approved these changes

2023-03-24 14:48 UTC, rorione approved these changes

2023-03-24 14:53 UTC, merged