App composed
Curo-app/curo pull request #8
Opened 2023-03-25 12:33 UTC by rorione

- Implemented navigation
- Implemented composition of all screens
- Removed a lot of junk

2023-03-25 12:34 UTC, rorione commented
![image](https://user-images.githubusercontent.com/21989227/227717532-87c2461f-43a8-4b4d-bb83-1b7928febd8b.png)
![image](https://user-images.githubusercontent.com/21989227/227717537-0e514a79-5f6b-4148-8c1f-85efb602f1a4.png)
![image](https://user-images.githubusercontent.com/21989227/227717543-b5b04e1c-7f9d-438f-8ee4-419057711b7d.png)
![image](https://user-images.githubusercontent.com/21989227/227717548-5d50f353-c4c9-40dc-858e-04f9db413c60.png)

2023-03-30 14:47 UTC, KhoDis requested changes

2023-03-30 14:47 UTC, Feyyus commented on app/src/main/java/io/github/curo/data/Note.kt
> +    val name: String,
А `name` нельзя что ли менять?

2023-03-30 14:47 UTC, Feyyus commented on app/src/main/java/io/github/curo/data/Note.kt
> +value class CollectionName(val name: String)
Почему value class, а не обычный класс с mutable `name`?

2023-03-30 14:47 UTC, Feyyus commented on app/src/main/java/io/github/curo/ui/AppScreen.kt
> +        navEditNoteSettings(noteViewModel, navController)
Возможно душу уже, но permute arguments?)

2023-03-30 14:47 UTC, KhoDis commented on app/src/main/java/io/github/curo/ui/AppScreen.kt
> +                visible = isBottomBarVisible,
Для каких случаев нужен `visible = false` для `NavigationBottomBar`?

2023-03-30 14:47 UTC, KhoDis commented on app/src/main/java/io/github/curo/ui/base/Collections.kt
> +            imageVector = Icons.Rounded.ArrowDropDown, contentDescription = "aboba"
aboba 🙀? В ресурсы нужно вынести

2023-03-30 14:47 UTC, KhoDis commented on app/src/main/java/io/github/curo/ui/base/SideMenu.kt
> +fun SideMenu(onItemClick: (MainScreen) -> Unit) {
https://m3.material.io/components/navigation-drawer/overview
ModalNavigationDrawer
Кажется, что такое уже есть?

2023-03-30 14:47 UTC, RuslanZaripov commented on app/src/main/java/io/github/curo/data/NotePatch.kt
> +class NotePatch(
Зачем этот класс `NotePatch`  нужен?

2023-03-30 14:47 UTC, RuslanZaripov commented on app/src/main/java/io/github/curo/data/NoteViewModel.kt
> +    val patchItem = items.map { items ->
За что отвечает `patchItem`?

2023-03-30 14:47 UTC, RuslanZaripov commented on app/src/main/java/io/github/curo/ui/AppScreen.kt
> +            FloatingActionButtonMenu(
За что отвечает `FloatingActionButtonMenu`?

2023-03-30 16:27 UTC, RuslanZaripov commented on app/src/main/java/io/github/curo/data/Screen.kt
> +sealed class MainScreen(
Можешь объяснить, что тут за паттерн используется, или статейку скинуть, если такая есть?

2023-03-30 16:27 UTC, RuslanZaripov commented on app/src/main/java/io/github/curo/ui/AppScreen.kt
> +                    outerNavHost.navigate("${menu.route}/${Random.nextInt()}") {
Random.nextInt()?

2023-03-30 18:22 UTC, rorione commented on app/src/main/java/io/github/curo/data/Note.kt
> +    val name: String,
это чисто вьюха для заметки без изменяемого состояния. когда хотим изменить заметку - создаем объект уже с изменяемыми состояниями (NotePatch)

2023-03-30 18:23 UTC, rorione commented on app/src/main/java/io/github/curo/data/Note.kt
> +value class CollectionName(val name: String)
Я так делал чисто для удобства, чтобы на уровне типов отличать случайную строку и имя коллекции. Ну и во вьюхе заметки изменяемые состояния лишние не нужны.

2023-03-30 18:24 UTC, rorione commented on app/src/main/java/io/github/curo/ui/AppScreen.kt
> +        navEditNoteSettings(noteViewModel, navController)
тут не понял

2023-03-30 18:34 UTC, rorione commented on app/src/main/java/io/github/curo/data/NotePatch.kt
> +class NotePatch(
Это изменяемая заметка со всеми состояниями. Этот класс должен юзаться в экранах изменения заметки и ее настройках и только в них

2023-03-30 18:35 UTC, rorione commented on app/src/main/java/io/github/curo/data/NoteViewModel.kt
> +    val patchItem = items.map { items ->
Это вьюха с мутабельными состояниями для изменения

2023-03-30 18:36 UTC, rorione commented on app/src/main/java/io/github/curo/ui/AppScreen.kt
> +            FloatingActionButtonMenu(
Это меню где выбираем какой тип заметки создать при нажатии на кнопку (где еще фон гаснет)

2023-03-30 22:57 UTC, rorione commented on app/src/main/java/io/github/curo/data/Screen.kt
> +sealed class MainScreen(
Чисто объектики для хранения route, просто в них сделал еще структуру вложенности, которая соответствует нашему приложению. Ща с новым мром немного ее изменил, но суть та же

2023-03-30 23:01 UTC, rorione commented on app/src/main/java/io/github/curo/ui/AppScreen.kt
> +            FloatingActionButtonMenu(
Оно тут находится из-за гаснущего фона как раз, который должен быть поверх всего остального, а кнопка поверх него

2023-03-30 23:01 UTC, rorione commented on app/src/main/java/io/github/curo/ui/AppScreen.kt
> +                visible = isBottomBarVisible,
переделал

2023-03-30 23:01 UTC, rorione commented on app/src/main/java/io/github/curo/ui/base/Collections.kt
> +            imageVector = Icons.Rounded.ArrowDropDown, contentDescription = "aboba"
done

2023-03-30 23:01 UTC, rorione commented on app/src/main/java/io/github/curo/ui/base/SideMenu.kt
> +fun SideMenu(onItemClick: (MainScreen) -> Unit) {
заменил на material3

2023-03-30 23:01 UTC, rorione commented on app/src/main/java/io/github/curo/ui/AppScreen.kt
> +                    outerNavHost.navigate("${menu.route}/${Random.nextInt()}") {
поправил

2023-03-31 07:36 UTC, KhoDis commented on app/src/main/java/io/github/curo/ui/AppScreen.kt
> +        navEditNoteSettings(noteViewModel, navController)
Ну, где-то `navController` первым идёт, где-то `collectionViewModel` первым идёт

2023-03-31 08:04 UTC, KhoDis approved these changes, later dismissed

2023-03-31 08:04 UTC, KhoDis commented on app/src/main/java/io/github/curo/data/Screen.kt
> +//object NoteOptionsScreen : Screen("note_options")
Такое в мастер стоит пушить разве?

2023-03-31 08:28 UTC, rorione commented on app/src/main/java/io/github/curo/data/Screen.kt
> +//object NoteOptionsScreen : Screen("note_options")
упс

2023-03-31 08:30 UTC, KhoDis approved these changes

2023-03-31 08:31 UTC, Ilya-Sib approved these changes

2023-03-31 08:41 UTC, merged